large_flask_application/myproject/models.py
from myproject import db

class Puppy(db.Model):
    __tablename__ = 'puppies'

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.Text)

    owner = db.relationship('Owner', backref = 'puppy', uselist = False)
    
    def __init__(self, name):
        self.name = name

    def __repr__(self):
        if self.owner:
            return f'Puppy name is {self.name} and owner is {self.owner.name}' 
        return f'Puppy name is {self.name} and has no owner yet!'

class Owner(db.Model):
    __tablename__ = 'owner'

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.Text)
    id_pup = db.Column(db.Integer, db.ForeignKey('puppies.id'))

    def __init__(self, name, id_pup):
        self.name = name
        self.id_pup = id_pup

    def __repr__(self):
        return f'Owner name: {self.name}'

large_flask_application/myproject/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,IntegerField,SubmitField

class AddOwnerForm(FlaskForm):

    name = StringField('Name of Owner: ')
    id_pup = IntegerField('Id of Puppy: ')
    submit = SubmitField('Add Owner')

large_flask_application/myproject/puppies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,IntegerField


class AddForm(FlaskForm):
    
    name = StringField('Name of Puppy: ')
    submit = SubmitField('Add Puppy')


class DelForm(FlaskForm):

    id = IntegerField('Id Number of Puppy to Remove: ')
    submit = SubmitField('Remove Puppy') 

large_flask_application/myproject/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)

basedir = os.path.abspath(os.path.dirname(__file__))

app.config['SECRET_KEY'] = 'mysecretkey'

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)


from myproject.puppies.views import puppies_blueprints
from myproject.owners.views import owners_blueprint


app.register_blueprint(owners_blueprint, url_prefix = '/owners')
app.register_blueprint(puppies_blueprints, url_prefix = '/puppies')

large_flask_application/myproject/owners/views.py
from flask import Blueprint, render_template,redirect,url_for
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import AddOwnerForm


owners_blueprint = Blueprint('owners',__name__,
                             template_folder='templates/owners')




@owners_blueprint.route('/add', methods = ['GET','POST'])
def add_owner():

    form = AddOwnerForm()

    if form.validate_on_submit():
        name = form.name.data
        id_pup = form.id_pup.data
        new_owner = Owner(name,id_pup)
        db.session.add(new_owner)
        db.session.commit()
        return redirect(url_for('puppies.list'))
    return render_template('add_owner.html', form=form)

large_flask_application/myproject/puppies/views.py
from flask import Blueprint,render_template,redirect,url_for
from myproject import db
from myproject.models import Puppy 
from myproject.puppies.forms import AddForm,DelForm

puppies_blueprints = Blueprint('puppies',__name__,
                               template_folder='templates/puppies')

@puppies_blueprints.route('/add', methods = ['GET','POST'])
def add_pup():
    form = AddForm()

    if form.validate_on_submit():
         
         name = form.name.data

         new_pup = Puppy(name)
         db.session.add(new_pup)
         db.session.commit()
         return redirect(url_for('puppies.list'))
    
    return render_template('add.html', form=form)

@puppies_blueprints.route('/list')
def list_pup():

    puppies = Puppy.query.all()

    return render_template('list.html', puppies = puppies)


@puppies_blueprints.route('/delete', methods = ['GET','POST'])
def del_pup():

    form = DelForm()

    if form.validate_on_submit():

        id = form.id.data
        pup = db.session.get(Puppy,id)
        db.session.delete(pup)
        db.session.commit()

        return redirect(url_for('puppies.list'))
    return render_template('delete.html', form=form)

large_flask_application/myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <title>Document</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{{url_for('index')}}">Home</a>
        <a class="nav-item nav-link" href="{{url_for('puppies.add_pup')}}"
          >Add Pup</a
        >
        <a class="nav-item nav-link" href="{{url_for('puppies.list_pup')}}"
          >List of Pups</a
        >
        <a class="nav-item nav-link" href="{{url_for('puppies.del_pup')}}"
          >Delete Pup</a
        >
        <a class="nav-item nav-link" href="{{url_for('owners.add_owner')}}"
          >Add Owner</a
        >
      </div>
    </nav>
    {%block content%} {%endblock%}
  </body>
</html>

large_flask_application/myproject/templates/home.html
{%extends 'base.html' %} {%block content%}
<div class="jumbotron">
  <h1>Welcome to our Adoption Page</h1>
  <p>Please select one of the links from the nav bar</p>
</div>

{%endblock%}